[build]
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"  # ok manter explícito

# Aplique a Edge "guarda" em /quiz (rota exata)...
[[edge_functions]]
  function = "guarda"
  path = "/quiz"

# ...e também em tudo dentro de /quiz/*
[[edge_functions]]
  function = "guarda"
  path = "/quiz/*"

# BLOQUEAR acesso público a qualquer coisa em /netlify/*
[[redirects]]
  from = "/netlify/*"
  to = "/"
  status = 404
  force = true

# ALIAS protegido: rota sob /quiz (envia o cookie mesmo com Path=/quiz)
[[redirects]]
  from = "/quiz/api/questoes"
  to = "/.netlify/functions/questoes"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"

