[build]
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"  # opcional; este já é o padrão

# Aplique a Edge Function "guarda" na rota exata /quiz
[[edge_functions]]
  function = "guarda"
  path = "/quiz"

# ...e em todos os recursos dentro de /quiz/*
[[edge_functions]]
  function = "guarda"
  path = "/quiz/*"

[functions]
  node_bundler = "esbuild"
